---
title: "Midterm"
author: "Salah El-Sadek (sne2114)"
output: github_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Problem #1

Import and clean dog weights data set, skipping first header row and omitting notes column. The column type for the column 'date' was changed to numeric then into date format, since 'date' values in excel are custom (numerically coded) formats, not date formats.

```{r read and tidy}
weights_tidy = 
  read_excel(
    "./data/dogweights_07sept2020.xlsx",
    skip = 1) %>%
  janitor::clean_names() %>%
  select(-x6) %>%
  mutate(
    date = as.numeric(date),
    date = as.Date(date, origin = "1899-12-30"))
```



```{r}
 
```

